services:
  - type: web
    name: landing-zone-docs
    env: static
    rootDir: docs
    buildCommand: yarn docs:build
    staticPublishPath: ./.vuepress/dist
    pullRequestPreviewsEnabled: true
    domains:
      - collie.cloudfoundation.org
      - landingzone.meshcloud.io # The old domain. We still keep it in case some old links point to it.
    buildFilter:
      paths:
        - docs/**/*
        - render.yaml
