name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: meshcloud/setup-collie@main
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs-unstable=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          file: default.nix
      - name: ensure all pre-commit hooks pass
        run: pre-commit run --all-files --show-diff-on-failure
      - name: compile kit
        run: collie kit compile