name: auto pull request
on:
  push:
    branches: [ "feature/auto-backporting" ]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pull Request in collie-hub repo

        run: |
          gh pr create --base main --head feature/auto-backporting --draft \
            --title "[latest likvid kits] update latest kits from likvid-cloudfoundation" \
            --body "The latest kits from likvid-cloudfoundation builds on the prod branch."; \
        env:
          GH_TOKEN: ${{ github.token }}