name: auto pull request
on:
  push:
    branches: [ "feature/auto-backporting" ]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - name: Create Pull Request in collie-hub repo
        run: gh pr create --base main --head feature/auto-backporting --title "[latest likvid kits] update latest kits from likvid-cloudfoundation" --body " The latest kits from likvid-cloudfoundation builds on the prod branch."
        # uses: peter-evans/create-pull-request@v6
        # with:
        #   commit-message: "feature: update azure kits from latest prod build"
        #   committer: GitHub Actions <github-actions@meshcloud.io>
        #   signoff: false
        #   base: main
        #   delete-branch: true
        #   title: "[latest likvid kits] update latest kits from likvid-cloudfoundation"
        #   body: |
        #     The latest kits from likvid-cloudfoundation builds on the prod branch.
        #     - This PR is updated automatically with changes, until merged
        #   draft: false
